server:
  port: 8083



spring:
  datasource:
    url: jdbc:mysql://localhost:3306/nbjy_admin_db?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8&autoReconnect=true&useSSL=false&allowMultiQueries=true
    username: root
    password: Star2035!
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-test-query: select version()
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true